<?php

namespace Kunstmaan\FormBundle\Repository\Export;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * LogItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogItemRepository extends EntityRepository
{
    /**
     * Modifies a QueryBuilder to filter out entities that have been exported successfully.
     *
     * @param QueryBuilder $builder
     * @param $originalEntityIdentifier
     * @param $originalEntityClass
     * @param string $exporterName
     *
     * @return QueryBuilder
     */
    public function modifyQueryBuilderToFilterOutExportedEntities(QueryBuilder $builder, $originalEntityIdentifier, $originalEntityClass, $exporterName)
    {
        $aliases = $builder->getRootAliases();
        $alias = reset($aliases);

        $builder->leftJoin('KunstmaanFormBundle:Export\LogItem', 'li', 'WITH', $alias.'.'.$originalEntityIdentifier." = li.exportableId AND li.exportableName = '".$originalEntityClass."' AND li.exporterName = '".$exporterName."'");
        $builder->andWhere('li.id IS NULL');

        return $builder;
    }
}
